### PR TITLE
Production release

### PR DESCRIPTION
**Pull request by MySmilingTurban**
Test Sheet [Smoke Test](https://docs.google.com/spreadsheets/d/11rCXiF5WKDjBepNqQX7UOKhqg9LP69AD838Z0BnNk20/edit?gid=658388068#gid=658388068)

Production Check list:  Tasks to be done on Firestore. 
[here](https://docs.google.com/spreadsheets/d/1ruDcKVhl0w1EsPXwxhiSQfyLadQGni35c_ZM1OQtbcw/edit?gid=0#gid=0)

### CODE REVIEW

**Review by amitojsingh — APPROVED** [review]

**Comment by Gauravjeetsingh** [comment]
I had a user already logged in dev app, on opening, I get empty profile page
image

and 5 coins with 0 words learnt
image

**Comment by Gauravjeetsingh** [comment]
Logged out and logged back in with google, profile page is working, but the words learnt is 0 with 5 nanak coins. The email id I am using is `gaurav.ishwerdas@gmail.com`

**Comment by Gauravjeetsingh** [comment]
On sign in with another account with email this time, `panda@ryaz.io` my name is shown as Gauravjeet === singh

Words learnt is still 0.

image

**Review by Gauravjeetsingh — CHANGES_REQUESTED** [review]
Words learnt in previous sessions are not visible now.

**Comment by amitojsingh** [comment]
Han ji veer ji it's because we have reset progress for all the users because earlier we had different approach with different user data so to avoid data conflict all the users progress was reset. 

We will reset this for Prod as well.

**Comment by amitojsingh** [comment]
Profile page is known issue we have moved profile page fix to next release.

**Comment by Gauravjeetsingh** [comment]
@amitojsingh and we dont want to reset the nanak coins? Just the words learnt? 

And other than this reset and unable to edit the profile page, everything is working fine for me. If that's known, I can go ahead and approve this PR.

**Comment by amitojsingh** [comment]
Han JI  Veer ji We can not reset nanak Coin. Nanak Coin is the most important thing that children care about. 
As discussed on Slack, we can deploy to prod with this known issue. 
https://khalis.slack.com/archives/C04LFE8G3PA/p1721688895623799?thread_ts=1721685233.782039&cid=C04LFE8G3PA

**Review by Gauravjeetsingh — APPROVED** [review]

**Comment by amitojsingh** [comment]
@MySmilingTurban Veer ji I have added index exemption. can you run migrations? which are listed here? 
https://docs.google.com/spreadsheets/d/1ruDcKVhl0w1EsPXwxhiSQfyLadQGni35c_ZM1OQtbcw/edit?gid=0#gid=0

**Comment by MySmilingTurban** [comment]
Sure ji, just ran both the scripts.

**Pull request merged**
