### PR TITLE
fix: design layout

### PR DESCRIPTION
**Pull request by amitojsingh**

### CODE REVIEW

**Comment by MySmilingTurban** [comment]
Start Learning button is not working after first load
can you please cross check
@amitojsingh

**Comment by amitojsingh** [comment]
on which device you are testing veer ji?

**Comment by MySmilingTurban** [comment]
> on which device you are testing veer ji?

both mobile and pc, it takes a reload to make it work or sometime wait of around 30 seconds

**Review by MySmilingTurban — APPROVED** [review]
Looks good to me!

**Review by MySmilingTurban — APPROVED** [review]
Looks good to me!

**Pull request merged**
